python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip --video_name 006 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip --video_name 007 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 008 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 009 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 010 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 011 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 012 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 013 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 014 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show --video_name 015 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 016 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 017 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 018 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 019 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 020 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 021 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 022 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing --video_name 023 --save_dir ./
