python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip1 --video_name 003 --save_dir ./animation_clip1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip1 --video_name 004 --save_dir ./animation_clip1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip1 --video_name 005 --save_dir ./animation_clip1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip2 --video_name 003 --save_dir ./animation_clip2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip2 --video_name 004 --save_dir ./animation_clip2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip2 --video_name 005 --save_dir ./animation_clip2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan1 --video_name 003 --save_dir ./caravan1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan1 --video_name 004 --save_dir ./caravan1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan1 --video_name 005 --save_dir ./caravan1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan2 --video_name 003 --save_dir ./caravan2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan2 --video_name 004 --save_dir ./caravan2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan2 --video_name 005 --save_dir ./caravan2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/corridor --video_name 003 --save_dir ./corridor
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/corridor --video_name 004 --save_dir ./corridor
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/corridor --video_name 005 --save_dir ./corridor
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass1 --video_name 003 --save_dir ./glass1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass1 --video_name 004 --save_dir ./glass1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass1 --video_name 005 --save_dir ./glass1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass2 --video_name 003 --save_dir ./glass2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass2 --video_name 004 --save_dir ./glass2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass2 --video_name 005 --save_dir ./glass2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar1 --video_name 003 --save_dir ./guitar1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar1 --video_name 004 --save_dir ./guitar1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar1 --video_name 005 --save_dir ./guitar1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar2 --video_name 003 --save_dir ./guitar2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar2 --video_name 004 --save_dir ./guitar2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar2 --video_name 005 --save_dir ./guitar2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar3 --video_name 003 --save_dir ./guitar3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar3 --video_name 004 --save_dir ./guitar3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar3 --video_name 005 --save_dir ./guitar3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor1 --video_name 003 --save_dir ./professor1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor1 --video_name 004 --save_dir ./professor1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor1 --video_name 005 --save_dir ./professor1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor2 --video_name 003 --save_dir ./professor2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor2 --video_name 004 --save_dir ./professor2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor2 --video_name 005 --save_dir ./professor2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor3 --video_name 003 --save_dir ./professor3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor3 --video_name 004 --save_dir ./professor3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor3 --video_name 005 --save_dir ./professor3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing1 --video_name 003 --save_dir ./skiing1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing1 --video_name 004 --save_dir ./skiing1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing1 --video_name 005 --save_dir ./skiing1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing2 --video_name 003 --save_dir ./skiing2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing2 --video_name 004 --save_dir ./skiing2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing2 --video_name 005 --save_dir ./skiing2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/sliding --video_name 003 --save_dir ./sliding
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/sliding --video_name 004 --save_dir ./sliding
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/sliding --video_name 005 --save_dir ./sliding
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show1 --video_name 003 --save_dir ./street_show1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show1 --video_name 004 --save_dir ./street_show1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show1 --video_name 005 --save_dir ./street_show1
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show2 --video_name 003 --save_dir ./street_show2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show2 --video_name 004 --save_dir ./street_show2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show2 --video_name 005 --save_dir ./street_show2
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show3 --video_name 003 --save_dir ./street_show3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show3 --video_name 004 --save_dir ./street_show3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show3 --video_name 005 --save_dir ./street_show3
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/surfing --video_name 003 --save_dir ./surfing
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/surfing --video_name 004 --save_dir ./surfing
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/surfing --video_name 005 --save_dir ./surfing
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/volleyball --video_name 003 --save_dir ./volleyball
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/volleyball --video_name 004 --save_dir ./volleyball
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/volleyball --video_name 005 --save_dir ./volleyball
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/wedding --video_name 003 --save_dir ./wedding
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/wedding --video_name 004 --save_dir ./wedding
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/wedding --video_name 005 --save_dir ./wedding

