python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/animation_clip2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/caravan2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/corridor --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/corridor --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/corridor --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/glass2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar3 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar3 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/guitar3 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor3 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor3 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/professor3 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/skiing2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/sliding --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/sliding --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/sliding --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show1 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show1 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show1 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show2 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show2 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show2 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show3 --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show3 --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/street_show3 --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/surfing --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/surfing --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/surfing --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/volleyball --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/volleyball --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/volleyball --video_name 005 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/wedding --video_name 003 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/wedding --video_name 004 --save_dir ./
python3 src/main.py --test_only --save_results --pre_train ./model/LGFN_x4.pt --dir_demo ../../dataset/wedding --video_name 005 --save_dir ./

